### PR TITLE
let slate widget handle text selection, pass it down to Editor

### PR DESCRIPTION
**Pull request by nileshgulia1**
This also fixes focus issues on RichtextWidget: #125

### CODE REVIEW

**Comment by tiberiuichim** [comment]
@nileshgulia1 I wonder how well it behaves with sidebar-based slate extensions, such as the Link plugin or the Footnote.

**Comment by nileshgulia1** [comment]
@tiberiuichim When using it as a widget in sidebar, I end up noticing issue regarding selection. As we rely on internal state for "selected" prop, passing it further to `Editor` causes bug related to selection. The prop never changes its value( see attached image) even if we move over the selection to different block/field. 

I propose we can let widget handle the outside selection and pass it to editor?

Screenshot 2021-07-27 at 5 01 10 PM

**Comment by tiberiuichim** [comment]
@nileshgulia1 Test it with passing `selected={true}` to SlateEditor

**Comment by nileshgulia1** [comment]
@tiberiuichim I managed to replicate and solve issue described in: https://github.com/eea/volto-slate/issues/125
By removing `handleoutsideClick` handler from my project's code.



> Test it with passing `selected={true}` to SlateEditor

[Here](https://github.com/eea/volto-slate/blob/c1f87bf896b63d22d0fd4d3def881eb64ffe918d/src/widgets/RichTextWidget.jsx#L41) we have already passed selected=true on `onClick` handler, but the value will never be `false`, even after changing focus to some other field.
This is in contrary to ordinary slate block, where it works fine.

However it doesn't cause any noticeable trouble, its used as a widget.

**Review by tiberiuichim — CHANGES_REQUESTED** [review]
@nileshgulia1 I can't create a link with the richtext widget, with the code in this PR, while it works with the develop branch.

**Comment by nileshgulia1** [comment]
hm.. seems a bit weird and non-critical for now. However I managed to solve the issue in project. Thanks!

**Pull request closed without merging**
