### PR TITLE
Now you can disable the sidebar of detached editor

### PR DESCRIPTION
**Pull request by iFlameing**
@tiberiuichim can you please review this.

### CODE REVIEW

**Review by tiberiuichim — CHANGES_REQUESTED** [review]
I think it's a mistake for the DetachedBlock to include the sidebar portal, it shouldn't include it. You can simply just remove that whole bit of code, no need for the prop. Unless you think that there might be a case where the sidebar would be useful, but I don't think so.

**Comment by iFlameing** [comment]
@tiberiuichim maybe you can just fix the Jenkins because I don't have access. And also I don't have the same prettier configuration according to project.

**Review by tiberiuichim — APPROVED** [review]

**Comment by silviubogan** [comment]
@iFlameing The ES Lint checks fail because there is an unused variable that should be removed:

https://github.com/eea/volto-slate/blob/5e959dc83a4ef4e979b2aedd4647d9a7eac44f5d/src/blocks/Text/TextBlockEdit.jsx#L291

**Comment by tiberiuichim** [comment]
Handled in #180

**Pull request closed without merging**
