### PR TITLE
Add "Delete table" contextual toolbar button

### PR DESCRIPTION
**Pull request by silviubogan**
image

### CODE REVIEW

**Comment by silviubogan** [comment]
# WIP

- [ ] the newly created rows/columns don't receive focus
- [ ] in a Slate-based rich text widget, if we have just one table, nothing else, pressing Enter in the last cell of the table does not move the cursor to a new paragraph, and this is the reason I believe we need to use inspiration from the well-thought [Plate table plugin](https://github.com/udecode/plate/tree/main/packages/elements/table/src)

@tiberiuichim should we do these tasks in this same PR?

**Comment by tiberiuichim** [comment]
@silviubogan Some cypress tests for this? Are they feasible?

**Comment by silviubogan** [comment]
> @silviubogan Some cypress tests for this? Are they feasible?

Yes, I think they are feasible.

**Comment by nileshgulia1** [comment]
I will write the cypress for this scenario.

**Comment by nileshgulia1** [comment]
Cypress are in place. Ready for merge @tiberiuichim @silviubogan

**Review by nileshgulia1 — APPROVED** [review]

**Pull request merged**
